/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun runnerCompiles() {
        // Minimal placeholder to keep project boot test.
        assertTrue(true)
    }
}
